-- ContentTypeIDs: (1) Page Instructions, (2) Form Instructions, (3) Field Definition

MERGE INTO dbo.CustomRichTextType AS Target
USING (VALUES
(1, 1, 'Platform Overview', 'Platform Overview'),
(2, 1, 'Disclaimer', 'Disclaimer'),
(3, 1, 'Home page', 'Home page'),
(4, 1, 'Help', 'Help'),
(5, 1, 'LabelsAndDefinitionsList', 'Labels and Definitions List'),
(6, 1, 'ManageUserParcels', 'Manage User Parcels'),
(7, 1, 'Training', 'Training'),
(8, 1, 'CustomPages', 'Custom Pages'),
(9, 1, 'MailMergeReport', 'Mail Merge Report'),
(10, 1, 'ParcelList', 'Parcel List'),
(11, 2, 'OnboardOverview', 'Onboard Overview'),
(12, 2, 'OnboardWaterAccountPINs', 'Water Account PINs'),
(13, 2, 'OnboardClaimParcels', 'Claim Parcels'),
(14, 2, 'WellRegistryIntro', 'Well Registry Intro'),
(15, 1, 'TagList', 'Tag List'),
(16, 1, 'BulkTagParcels', 'Bulk Tag Parcels'),
(17, 1, 'WaterAccounts', 'Water Accounts'),
(18, 1, 'WaterTransactions', 'Water Transactions'),
(19, 1, 'WaterTransactionCreate', 'Water Transaction Create'),
(20, 1, 'WaterTransactionBulkCreate', 'Water Transaction Bulk Create'),
(21, 1, 'WaterTransactionCSVUploadSupply', 'Water Transaction CSV Upload Supply'),
(22, 1, 'WaterTransactionHistory', 'WaterTransaction History'),
(23, 3, 'WaterAccount', 'Water Account'),
(24, 3, 'Tag', 'Tag'),
(25, 3, 'WaterAccountPIN', 'Water Account PIN'),
(26, 3, 'SupplyType', 'Supply Type'),
(27, 3, 'TotalSupply', 'Total Supply'),
(28, 3, 'TotalUsage', 'Total Usage'),
(29, 3, 'TransactionType', 'Transaction Type'),
(30, 3, 'EffectiveDate', 'Effective Date'),
(31, 1, 'ReportingPeriodConfiguration', 'Reporting Period Configuration'),
(32, 1, 'WaterSupplyConfiguration', 'Water Supply Configuration'),
(33, 1, 'WaterLevelsConfiguration', 'Water Levels Configuration'),
(34, 1, 'TradingConfiguration', 'Trading Configuration'),
(35, 1, 'ScenariosConfiguration', 'Scenarios Configuration'),
(36, 1, 'WellRegistryConfiguration', 'Well Registry Configuration'),
(37, 1, 'PermissionsConfiguration', 'Permissions Configuration'),
(38, 1, 'GeospatialDataConfiguration', 'Geospatial Data Configuration'),
(39, 1, 'CustomPagesConfiguration', 'Custom Pages Configuration'),
(40, 2, 'UpdateParcelsUpload', 'Update Parcels Upload'),
(41, 2, 'UpdateParcelsReviewParcels', 'Update Parcels Review Parcels'),
(42, 2, 'UpdateParcelsConfirm', 'Update Parcels Confirm'),
(43, 2, 'AccountReconciliation', 'Account Reconciliation'),
(44, 1, 'Footer', 'Footer'),
(45, 1, 'EditAccounts', 'Edit Accounts'),
(46, 1, 'EditUsers', 'Edit Users'),
(47, 1, 'AccountActivity', 'Account Activity'),
(48, 1, 'UsageByParcel', 'Usage By Parcel'),
(49, 1, 'AccountMap', 'Account Map'),
(50, 1, 'ChangeParcelOwnership', 'Change Parcel Ownership'),
(51, 2, 'WellBulkUpload', 'Well Bulk Upload'),
(52, 1, 'WellName', 'Well Name'),
(53, 1, 'CountyWellPermitNo', 'County Well Permit No'),
(54, 1, 'StateWCRNo', 'State WCR No'),
(55, 1, 'WellDepth', 'Well Depth (ft)'),
(56, 1, 'DateDrilled', 'Date Drilled'),
(57, 1, 'WaterTransactionCsvUploadUsage', 'Water Transaction CSV Upload Usage'),
(58, 3, 'APNColumn', 'APN Column'),
(59, 3, 'ValueColumn', 'Value Column'),
(60, 3, 'UsageType', 'Water Measurement Type'),
(61, 1, 'Wells', 'Wells'),
(62, 1, 'ExternalMapLayers', 'External Map Layers'),
(63, 3, 'ExternalMapLayersType', 'External Map Layers Type'),
(64, 1, 'ExternalMapLayersEdit', 'External Map Layers Edit'),
(65, 3, 'ExternalMapLayersName', 'External Map Layers Name'),
(66, 3, 'ExternalMapLayersMinimumZoom', 'External Map Layers Minimum Zoom'),
(67, 1, 'OurGeographies', 'Our Geographies'),
(68, 3, 'PopUpField', 'Pop-up Field'),
(69, 1, 'OpenETSyncIntegration', 'OpenET Sync Integration'),
(70, 1, 'OpenETInstructions', 'Openet Instructions'),
(71, 1, 'UsageEstimates', 'Usage Estimates'),
(72, 2, 'LastSuccessfulSyncDate', 'Last Successful Sync Date'),
(73, 2, 'LastSyncDate', 'Last Sync Date'),
(74, 2, 'DateFinalized', 'Date Finalized'),
(75, 3, 'EstimateDate', 'Estimate Date'),
(76, 1, 'ZoneGroupsEdit', 'Zone Groups Edit'),
(77, 1, 'ZoneGroupConfiguration', 'Zone Group Configuration'),
(78, 1, 'ZoneGroupCSVUploader', 'Zone Group CSV Uploader'),
(79, 3, 'ZoneColumn', 'Zone Column'),
(80, 1, 'ZoneGroupList', 'Zone Group List'),
(81, 1, 'HomeAboutCopy', 'Home About Copy'),
(82, 1, 'WaterAccountBudgetReport', 'Water Account Budgets Report'),
(83, 1, 'CustomPageEditProperties', 'Custom Page Edit Properties'),
(84, 1, 'ZoneGroupUsageChart', 'Historical Water Usage by Zone'),
(85, 2, 'ModalUpdateWaterAccountInformation', 'Update Water Account Information'),
(86, 2, 'ModalCreateNewWaterAccount', 'Create a new Water Account'),
(87, 2, 'ModalAddParcelToWaterAccount', 'Add Parcel to Water Account'),
(88, 2, 'ModalMergeWaterAccounts', 'Merge Water Accounts'),
(89, 2, 'ModalUpdateWaterAccountParcels', 'Update Water Account Parcels'),
(90, 3, 'WaterAccountMergeType', 'Merge Type'),
(91, 1, 'GeographyAbout', 'Geography About'),
(92, 1, 'GeographyAllocations', 'Geography Allocations'),
(93, 1, 'GeographyWaterLevels', 'Geography Water Levels'),
(94, 1, 'GeographySupport', 'Geography Support'),
(95, 1, 'MonitoringWellsGrid', 'MonitoringWellsGrid'),
(96, 1, 'WaterDashboardWaterAccounts', 'Water Dashboard Water Accounts'),
(97, 1, 'AddAWellScenario', 'Add a Well Scenario'),
(98, 1, 'AllocationPlanEdit', 'Allocation Plan Edit'),
(99, 1, 'AllocationPlansConfigure', 'Configure Allocation Plans'),
(100, 1, 'CloneAllocationPlan', 'Clone Allocation Plan'),
(101, 1, 'AccountAllocationPlans', 'Account Allocation Plans'),
(102, 1, 'RechargeScenario', 'Recharge Scenario'),
(103, 1, 'PostToSupply', 'Post to Supply'),
(104, 3, 'OpenETSyncVariable', 'OpenET Sync Variable'),
(105, 1, 'LandownerParcelIndex', 'Landowner Parcel Index'),
(106, 1, 'ScenarioPlanner', 'Scenario Planner'),
(107, 1, 'ScenarioPlannerGET', 'Scenario Planner GET'),
(108, 1, 'ScenarioPlannerScenarioRuns', 'Scenario Runs'),
(109, 1, 'ActivityCenter', 'Activity Center'),
(110, 1, 'WaterAccountSuggestions', 'Water Account Suggestions'),
(111, 2, 'ModalReviewWaterAccountSuggestion', 'Review Water Account Suggestion'),
(112, 1, 'WellRegistryConfigurationPage', 'Well Registry Configuration Page'),
(113, 2, 'WellRegistryMapYourWell', 'Well Registry Map Your Well'),
(114, 2, 'WellRegistryConfirmWellLocation', 'Well Registry Confirm Well Location'),
(115, 2, 'WellRegistryIrrigatedParcels', 'Well Registry Irrigated Parcels'),
(116, 2, 'WellRegistryContacts', 'Well Registry Contacts'),
(117, 2, 'WellRegistryBasicInformation', 'Well Registry Basic Information'),
(118, 2, 'WellRegistrySupportingInformation', 'Well Registry Supporting Information'),
(119, 2, 'WellRegistryAttachments', 'Well Registry Attachments'),
(120, 2, 'WellRegistrySubmit', 'Well Registry Submit'),
(121, 3, 'WellRegistryFieldWellName', 'WellRegistryFieldWellName'),
(122, 3, 'WellRegistryFieldSWN', 'WellRegistryFieldSWN'),
(123, 3, 'WellRegistryFieldWCR', 'WellRegistryFieldWCR'),
(124, 3, 'WellRegistryFieldCountyWellPermit', 'WellRegistryFieldCountyWellPermit'),
(125, 3, 'WellRegistryFieldDateDrilled', 'WellRegistryFieldDateDrilled'),
(126, 3, 'WellRegistryFieldWaterUseDescriptionAgricultural', 'WellRegistryFieldWaterUseDescriptionAgricultural'),
(127, 3, 'WellRegistryFieldWaterUseDescriptionStockWatering', 'WellRegistryFieldWaterUseDescriptionStockWatering'),
(128, 3, 'WellRegistryFieldWaterUseDescriptionDomestic', 'WellRegistryFieldWaterUseDescriptionDomestic'),
(129, 3, 'WellRegistryFieldWaterUseDescriptionPublicMunicipal', 'WellRegistryFieldWaterUseDescriptionPublicMunicipal'),
(130, 3, 'WellRegistryFieldWaterUseDescriptionPrivateMunicipal', 'WellRegistryFieldWaterUseDescriptionPrivateMunicipal'),
(131, 3, 'WellRegistryFieldWaterUseDescriptionOther', 'WellRegistryFieldWaterUseDescriptionOther'),
(132, 3, 'WellRegistryFieldTopOfPerforations', 'Top of Perforations'),
(133, 3, 'WellRegistryFieldBottomOfPerforations', 'Bottom of Perforations'),
(134, 3, 'WellRegistryFieldMaximumFlow', 'WellRegistryFieldMaximumFlow'),
(135, 3, 'WellRegistryFieldTypicalFlow', 'WellRegistryFieldTypicalFlow'),
(136, 1, 'ManageReviewSubmittedWells', 'ManageReviewSubmittedWells'),
(137, 1, 'LandownerWellList', 'Landowner Well List'),
(138, 1, 'ManageAllWellRegistrations', 'ManageAllWellRegistrations'),
(139, 1, 'FormAsteriskExplanation', 'FormAsteriskExplanation'),
(140, 1, 'WellRegistryIncompleteText', 'WellRegistryIncompleteText'),
(141, 1, 'ReferenceWellsList', 'Reference Wells List'),
(142, 2, 'ReferenceWellsUploader', 'Reference Wells Uploader'),
(143, 1, 'LandingPageBody', 'Landing Page Body'),
(144, 1, 'LandingPageUserCard', 'Landing Page User Card'),
(145, 1, 'LandingPageParcelCard', 'Landing Page Parcel Card'),
(146, 1, 'LandingPageWellCard', 'Landing Page Well Card'),
(147, 1, 'LandingPageWaterAccountCard', 'Landing Page Water Account Card'),
(148, 1, 'LandingPageOverview', 'Landing Page Overview'),
(149, 1, 'LandingPageAllocationPlans', 'Landing Page Allocation Plans'),
(150, 1, 'LandingPageWaterLevels', 'Landing Page Water Levels'),
(151, 1, 'LandingPageContact', 'Landing Page Contact'),
(152, 1, 'ConfigureLandingPage', 'ConfigureLandingPage'),
(153, 1, 'HomepageUpdateProfileLink', 'Homepage Update Profile Link'),
(154, 1, 'HomepageGrowerGuideLink', 'Homepage Grower Guide Link'),
(155, 1, 'HomepageGeographiesLink', 'Homepage Geographies Link'),
(156, 1, 'HomepageClaimWaterAccountsPanel', 'Homepage Claim Water Accounts Panel'),
(157, 3, 'ParcelStatus', 'Parcel Status'),
(158, 1, 'OnboardOverviewContent', 'Onboard Overview Content'),
(159, 1, 'ParcelBulkActions', 'Parcel Bulk Actions'),
(160, 1, 'MeterList', 'Meter List'),
(161, 3, 'SerialNumber', 'Serial Number'),
(162, 1, 'MeterConfiguration', 'Meter Configuration'),
(163, 1, 'Acknowledgements', 'Acknowledgements'),
(164, 1, 'AdminGeographyEditForm', 'Admin Geography Edit Form'),
(165, 1, 'LandingPageConfigure', 'Landing Page Configure'),
(166, 1, 'MeterDataConfigure', 'Meter Data Configure'),
(167, 1, 'AllocationPlanConfigureCard', 'Allocation Plan Configure Card'),
(168, 2, 'WellStatus', 'Well Status'),
(169, 1, 'UpdateWellInfo', 'Update Well Info'),
(170, 1, 'UpdateWellLocation', 'UpdateWellLocation'),
(171, 1, 'UpdateWellIrrigatedParcels', 'Update Well Irrigated Parcels'),
(172, 1, 'AdminFAQ', 'Admin Frequently Asked Questions'),
(173, 1, 'GeneralFAQ', 'General Frequently Asked Questions'),
(174, 1, 'WaterAccountCustomAttributesEdit', 'Edit Water Account Attributes'),
(175, 1, 'ParcelCustomAttributesEdit', 'Edit Parcel Attributes'),
(176, 1, 'WaterDashboardLink', 'Water Dashboard Link'),
(177, 1, 'WaterManagerGuideLink', 'Water Manager Guide Link'),
(178, 1, 'ReviewParcelChanges', 'Review Parcel Changes'),
(179, 1, 'WaterAccountRequestChanges', 'Request Water Account Changes'),
(180, 1, 'WaterAccountRequestChangesCertification', 'Request Water Account Changes Certification'),
(181, 1, 'ConsolidateWaterAccountsDisclaimer', 'Consolidate Water Accounts Disclaimer'),
(182, 1, 'KernScenarioModel', 'Kern Scenario Model'),
(183, 1, 'MercedWaterResourcesModel', 'Merced Water Resources Model'),
(184, 1, 'YoloScenarioModel', 'Yolo Scenario Model'),
(185, 1, 'ConfigureGeographySetup', 'Configure Geography Setup'),
(186, 1, 'ConfigureCustomAttributes', 'Configure Custom Attributes'),
(187, 1, 'ConfigureWaterManagers', 'Configure Water Managers'),
(188, 1, 'RasterUploadGuidance', 'Raster Upload Guidance'),
(189, 1, 'WaterDashboardParcels', 'Water Dashboard Parcels'),
(190, 1, 'WaterDashboardWells', 'Water Dashboard Wells'),
(191, 1, 'RequestSupport', 'Request Support'),
(192, 1, 'FeeCalculatorStepOne', 'Fee Calculator Step One'),
(193, 3, 'FeeCalculatorSurfaceWater', 'DO YOU RECEIVE SURFACE WATER?'),
(194, 1, 'FeeCalculatorStepTwo', 'Fee Calculator Step Two'),
(195, 1, 'FeeCalculatorStepThree', 'Fee Calculator Step Three'),
(196, 1, 'FeeCalculatorAboutFeeStructures', 'Fee Calculator About Fee Structures'),
(197, 3, 'FeeCalculatorIncentivePayment', 'Incentive Payment'),
(198, 1, 'FeeCalculatorWhatIsConsumedGroundwater', 'What is Consumed Groundwater?'),
(199, 1, 'FeeCalculatorYourData', 'Your Data'),
(200, 1, 'FeeCalculatorAcres', 'Acres'),
(201, 3, 'FeeCalculatorFallowingSelfDirected', 'Fallowing (Self-Directed)'),
(202, 3, 'FeeCalculatorCoverCroppingSelfDirected', 'Cover Cropping (Self-Directed)'),
(203, 3, 'FeeCalculatorTemporaryFallowingLandFallowingProgram', 'Incentivized Fallowing Program'),
(204, 3, 'FeeCalculatorRotationalExtendedFallowingMLRP', 'MLRP Rotational/Extended Fallowing'),
(205, 3, 'FeeCalculatorRotationalExtendedFallowingInDesignatedBufferZonesMLRP', 'Rotational Extended Fallowing in Designated Buffer Zones (MLRP)'),
(206, 3, 'FeeCalculatorOrchardSwaleRewildingMLRP', 'MLRP Orchard Swale Rewilding'),
(207, 3, 'FeeCalculatorFloodplainReconnectionAndRelatedSpreadingAndRechargeMLRP', 'MLRP Floodplain Reconnection and Related Spreading and Recharge'),
(208, 3, 'FeeCalculatorFloodflowSpreadingOnNonFloodplainLandsMLRP', 'MLRP Flood Flow Spreading'),
(209, 3, 'FeeCalculatorStorageOrRechargeBasinsMLRP', 'MLRP Storage/Recharge Basins'),
(210, 1, 'LandingPageFeeCalculator', 'Fee Calculator'),
(211, 1, 'NewsAndAnnouncements', 'News and Announcements'),
(212, 1, 'ReviewSelfReportList', 'Review Self Report List'),
(213, 1, 'SubmitSelfReportDisclaimer', 'Submit Self Report Disclaimer'),
(214, 1, 'SelfReportEditorInstructions', 'Self Report Editor Instructions'),
(215, 1, 'GeographyUserList', 'Geography User List'),
(216, 1, 'WaterDashboardUsageLocations', 'Water Dashboard Usage Locations'),
(217, 3, 'UsageLocation', 'Usage Location'),
(218, 2, 'ModalUpdateWellParcel', 'Update Well Parcel'),
(219, 1, 'UsageLocationSupplyAndUsageMenu', 'Usage Location Supply and Usage Menu'),
(220, 1, 'EditMeterReading', 'Add Meter Reading'),
(221, 2, 'EditMeterReadingForm', 'Edit Meter Reading Form'),
(222, 1, 'BulkSetWaterMeasurementForm', 'Bulk Set Water Measurement Form'),
(223, 1, 'BulkUploadMeterReadings', 'Bulk Upload Meter Readings'),
(224, 1, 'StatementList', 'Statement List'),
(225, 1, 'NewStatementBatch', 'New Statement Batch'),
(226, 1, 'StatementTemplateList', 'Statement Template List'),
(227, 1, 'StatementTemplateConfiguration', 'Statement Template Configuration'),
(228, 1, 'FallowSelfReportingList', 'Fallow Self Reports'),
(229, 1, 'FallowSelfReportingInstructions', 'Fallow Self-Reporting'),
(230, 2, 'ModalUpdateWaterAccountContactInfo', 'Update Water Account Contact Info'),
(231, 1, 'CoverCropSelfReportingList', 'Cover Crop Self Reports'),
(232, 1, 'CoverCropSelfReportingInstructions', 'Cover Crop Self-Reporting'),
(233, 1, 'CoverCropSelfReportingReview', 'Review Cover Crop Self Reports'),
(234, 1, 'CoverCropSelfReportingSubmitAttestation', 'Submit Cover Crop Attestation'),
(235, 1, 'FallowSelfReportingSubmitAttestation', 'Submit Fallow Attestation'),
(236, 1, 'FallowSelfReportingReview', 'Review Fallow Self Reports'),
(237, 1, 'UsageLocationTypeConfiguration', 'Usage Location Type Configuration'),
(238, 1, 'UsageLocationTypeEdit', 'Usage Location Type Edit'),
(239, 1, 'UsageLocationBulkActions', 'Usage Location Bulk Actions'),
(240, 1, 'WaterDashboardActivityCenter', 'Water Dashboard Activity Center'),
(241, 1, 'UsageLocationGdbUpload', 'Usage Location GDB Upload'),
(242, 1, 'UsageLocationUploadReview', 'Usage Location Upload Review'),
(243, 1, 'Self Reporting Configuration', 'Self Reporting Configuration'),
(244, 3, 'UsageLocationType', 'Usage Location Type'),
(245, 1, 'WaterAccountContactList', 'Water Account Contact List'),
(246, 1, 'WaterAccountContactDetail', 'Water Account Contact Detail'),
(247, 1, 'WaterAccountContactCreateModal', 'Water Account Contact Create Modal'),
(248, 1, 'WaterAccountContactUpdateModal', 'Water Account Contact Update Modal'),
(249, 1, 'TermsOfService', 'Terms of Service'),
(250, 1, 'APIKey', 'API Key'),
(251, 1, 'GettingStartedWithTheAPI', 'Getting Started with the API')
)
AS Source (CustomRichTextTypeID, ContentTypeID, CustomRichTextTypeName, CustomRichTextTypeDisplayName)
ON Target.CustomRichTextTypeID = Source.CustomRichTextTypeID
WHEN MATCHED THEN
UPDATE SET
	ContentTypeID = Source.ContentTypeID,
	CustomRichTextTypeName = Source.CustomRichTextTypeName,
	CustomRichTextTypeDisplayName = Source.CustomRichTextTypeDisplayName
WHEN NOT MATCHED BY TARGET THEN
	INSERT (CustomRichTextTypeID, ContentTypeID, CustomRichTextTypeName, CustomRichTextTypeDisplayName)
	VALUES (CustomRichTextTypeID, ContentTypeID, CustomRichTextTypeName, CustomRichTextTypeDisplayName)
WHEN NOT MATCHED BY SOURCE THEN
	DELETE;
