-- ContentTypeIDs: (1) Page Instructions, (2) Form Instructions, (3) Field Definition

MERGE INTO dbo.CustomRichTextType AS Target
USING (VALUES
(1, 1, 'Platform Overview', 'Platform Overview'),
(2, 1, 'Disclaimer', 'Disclaimer'),
(3, 1, 'Home page', 'Home page'),
(4, 1, 'Help', 'Help'),
(5, 1, 'LabelsAndDefinitionsList', 'Labels and Definitions List'),
(6, 1, 'ManageUserParcels', 'Manage User Parcels'),
(7, 1, 'Training', 'Training'),
(8, 1, 'CustomPages', 'Custom Pages'),
(9, 1, 'MailMergeReport', 'Mail Merge Report'),
(10, 1, 'ParcelList', 'Parcel List'),
(11, 2, 'OnboardOverview', 'Onboard Overview'),
(12, 2, 'OnboardWaterAccountPINs', 'Water Account PINs'),
(13, 2, 'OnboardClaimParcels', 'Claim Parcels'),
(14, 2, 'WellRegistryIntro', 'Well Registry Intro'),
(15, 1, 'TagList', 'Tag List'),
(16, 1, 'BulkTagParcels', 'Bulk Tag Parcels'),
(17, 1, 'WaterAccounts', 'Water Accounts'),
(18, 1, 'WaterTransactions', 'Water Transactions'),
(19, 1, 'WaterTransactionCreate', 'Water Transaction Create'),
(20, 1, 'WaterTransactionBulkCreate', 'Water Transaction Bulk Create'),
(21, 1, 'WaterTransactionCSVUploadSupply', 'Water Transaction CSV Upload Supply'),
(22, 1, 'WaterTransactionHistory', 'WaterTransaction History'),
(23, 3, 'WaterAccount', 'Water Account'),
(24, 3, 'Tag', 'Tag'),
(25, 3, 'WaterAccountPIN', 'Water Account PIN'),
(26, 3, 'SupplyType', 'Supply Type'),
(27, 3, 'TotalSupply', 'Total Supply'),
(28, 3, 'TotalUsage', 'Total Usage'),
(29, 3, 'TransactionType', 'Transaction Type'),
(30, 3, 'EffectiveDate', 'Effective Date'),
(31, 1, 'ReportingPeriodConfiguration', 'Reporting Period Configuration'),
(32, 1, 'WaterSupplyConfiguration', 'Water Supply Configuration'),
(33, 1, 'WaterLevelsConfiguration', 'Water Levels Configuration'),
(34, 1, 'TradingConfiguration', 'Trading Configuration'),
(35, 1, 'ScenariosConfiguration', 'Scenarios Configuration'),
(36, 1, 'WellRegistryConfiguration', 'Well Registry Configuration'),
(37, 1, 'PermissionsConfiguration', 'Permissions Configuration'),
(38, 1, 'GeospatialDataConfiguration', 'Geospatial Data Configuration'),
(39, 1, 'CustomPagesConfiguration', 'Custom Pages Configuration'),
(40, 2, 'UpdateParcelsUpload', 'Update Parcels Upload'),
(41, 2, 'UpdateParcelsReviewParcels', 'Update Parcels Review Parcels'),
(42, 2, 'UpdateParcelsConfirm', 'Update Parcels Confirm'),
(43, 2, 'AccountReconciliation', 'Account Reconciliation'),
(44, 1, 'Footer', 'Footer'),
(45, 1, 'EditAccounts', 'Edit Accounts'),
(46, 1, 'EditUsers', 'Edit Users'),
(47, 1, 'AccountActivity', 'Account Activity'),
(48, 1, 'UsageByParcel', 'Usage By Parcel'),
(49, 1, 'AccountMap', 'Account Map'),
(50, 1, 'ChangeParcelOwnership', 'Change Parcel Ownership'),
(51, 2, 'WellBulkUpload', 'Well Bulk Upload'),
(52, 1, 'WellName', 'Well Name'),
(53, 1, 'CountyWellPermitNo', 'County Well Permit No'),
(54, 1, 'StateWCRNo', 'State WCR No'),
(55, 1, 'WellDepth', 'Well Depth'),
(56, 1, 'DateDrilled', 'Date Drilled'),
(57, 1, 'WaterTransactionCsvUploadUsage', 'Water Transaction CSV Upload Usage'),
(58, 3, 'APNColumn', 'APN Column'),
(59, 3, 'ValueColumn', 'Value Column'),
(60, 3, 'UsageType', 'Water Measurement Type'),
(61, 1, 'Wells', 'Wells'),
(62, 1, 'ExternalMapLayers', 'External Map Layers'),
(63, 3, 'ExternalMapLayersType', 'External Map Layers Type'),
(64, 1, 'ExternalMapLayersEdit', 'External Map Layers Edit'),
(65, 3, 'ExternalMapLayersName', 'External Map Layers Name'),
(66, 3, 'ExternalMapLayersMinimumZoom', 'External Map Layers Minimum Zoom'),
(67, 1, 'OurGeographies', 'Our Geographies'),
(68, 3, 'PopUpField', 'Pop-up Field'),
(69, 1, 'OpenETSyncIntegration', 'OpenET Sync Integration'),
(70, 1, 'OpenETInstructions', 'Openet Instructions'),
(71, 1, 'UsageEstimates', 'Usage Estimates'),
(72, 2, 'LastSuccessfulSyncDate', 'Last Successful Sync Date'),
(73, 2, 'LastSyncDate', 'Last Sync Date'),
(74, 2, 'DateFinalized', 'Date Finalized'),
(75, 3, 'EstimateDate', 'Estimate Date'),
(76, 1, 'ZoneGroupsEdit', 'Zone Groups Edit'),
(77, 1, 'ZoneGroupConfiguration', 'Zone Group Configuration'),
(78, 1, 'ZoneGroupCSVUploader', 'Zone Group CSV Uploader'),
(79, 3, 'ZoneColumn', 'Zone Column'),
(80, 1, 'ZoneGroupList', 'Zone Group List'),
(81, 1, 'HomeAboutCopy', 'Home About Copy'),
(82, 1, 'WaterAccountBudgetReport', 'Water Account Budgets Report'),
(83, 1, 'CustomPageEditProperties', 'Custom Page Edit Properties'),
(84, 1, 'ZoneGroupUsageChart', 'Historical Water Usage by Zone'),
(85, 2, 'ModalUpdateWaterAccountInformation', 'Update Water Account Information'),
(86, 2, 'ModalCreateNewWaterAccount', 'Create a new Water Account'),
(87, 2, 'ModalAddParcelToWaterAccount', 'Add Parcel to Water Account'),
(88, 2, 'ModalMergeWaterAccounts', 'Merge Water Accounts'),
(89, 2, 'ModalUpdateWaterAccountParcels', 'Update Water Account Parcels'),
(90, 3, 'WaterAccountMergeType', 'Merge Type'),
(91, 1, 'GeographyAbout', 'Geography About'),
(92, 1, 'GeographyAllocations', 'Geography Allocations'),
(93, 1, 'GeographyWaterLevels', 'Geography Water Levels'),
(94, 1, 'GeographySupport', 'Geography Support'),
(95, 1, 'MonitoringWellsGrid', 'MonitoringWellsGrid'),
(96, 1, 'WaterAccountDashboard', 'Water Account Dashboard'),
(97, 1, 'AddAWellScenario', 'Add a Well Scenario'),
(98, 1, 'AllocationPlanEdit', 'Allocation Plan Edit'),
(99, 1, 'AllocationPlansConfigure', 'Configure Allocation Plans'),
(100, 1, 'CloneAllocationPlan', 'Clone Allocation Plan'),
(101, 1, 'AccountAllocationPlans', 'Account Allocation Plans'),
(102, 1, 'RechargeScenario', 'Recharge Scenario'),
(103, 1, 'PostToSupply', 'Post to Supply'),
(104, 3, 'OpenETSyncVariable', 'OpenET Sync Variable'),
(105, 1, 'LandownerParcelIndex', 'Landowner Parcel Index'),
(106, 1, 'ScenarioPlanner', 'Scenario Planner'),
(107, 1, 'ScenarioPlannerGET', 'Scenario Planner GET'),
(108, 1, 'ScenarioPlannerScenarioRuns', 'Scenario Runs'),
(109, 1, 'ActivityCenter', 'Activity Center'),
(110, 1, 'WaterAccountSuggestions', 'Water Account Suggestions'),
(111, 2, 'ModalReviewWaterAccountSuggestion', 'Review Water Account Suggestion'),
(112, 1, 'WellRegistryConfigurationPage', 'Well Registry Configuration Page'),
(113, 2, 'WellRegistryMapYourWell', 'Well Registry Map Your Well'),
(114, 2, 'WellRegistryConfirmWellLocation', 'Well Registry Confirm Well Location'),
(115, 2, 'WellRegistryIrrigatedParcels', 'Well Registry Irrigated Parcels'),
(116, 2, 'WellRegistryContacts', 'Well Registry Contacts'),
(117, 2, 'WellRegistryBasicInformation', 'Well Registry Basic Information'),
(118, 2, 'WellRegistrySupportingInformation', 'Well Registry Supporting Information'),
(119, 2, 'WellRegistryAttachments', 'Well Registry Attachments'),
(120, 2, 'WellRegistrySubmit', 'Well Registry Submit'),
(121, 3, 'WellRegistryFieldWellName', 'WellRegistryFieldWellName'),
(122, 3, 'WellRegistryFieldSWN', 'WellRegistryFieldSWN'),
(123, 3, 'WellRegistryFieldWCR', 'WellRegistryFieldWCR'),
(124, 3, 'WellRegistryFieldCountyWellPermit', 'WellRegistryFieldCountyWellPermit'),
(125, 3, 'WellRegistryFieldDateDrilled', 'WellRegistryFieldDateDrilled'),
(126, 3, 'WellRegistryFieldWaterUseDescriptionAgricultural', 'WellRegistryFieldWaterUseDescriptionAgricultural'),
(127, 3, 'WellRegistryFieldWaterUseDescriptionStockWatering', 'WellRegistryFieldWaterUseDescriptionStockWatering'),
(128, 3, 'WellRegistryFieldWaterUseDescriptionDomestic', 'WellRegistryFieldWaterUseDescriptionDomestic'),
(129, 3, 'WellRegistryFieldWaterUseDescriptionPublicMunicipal', 'WellRegistryFieldWaterUseDescriptionPublicMunicipal'),
(130, 3, 'WellRegistryFieldWaterUseDescriptionPrivateMunicipal', 'WellRegistryFieldWaterUseDescriptionPrivateMunicipal'),
(131, 3, 'WellRegistryFieldWaterUseDescriptionOther', 'WellRegistryFieldWaterUseDescriptionOther'),
(132, 3, 'WellRegistryFieldTopOfPerforations', 'WellRegistryFieldTopOfPerforations'),
(133, 3, 'WellRegistryFieldBottomOfPerforations', 'WellRegistryFieldBottomOfPerforations'),
(134, 3, 'WellRegistryFieldMaxiumumFlow', 'WellRegistryFieldMaxiumumFlow'),
(135, 3, 'WellRegistryFieldTypicalFlow', 'WellRegistryFieldTypicalFlow'),
(136, 1, 'ManageReviewSubmittedWells', 'ManageReviewSubmittedWells'),
(137, 1, 'LandownerWellList', 'Landowner Well List'),
(138, 1, 'ManageAllWellRegistrations', 'ManageAllWellRegistrations'),
(139, 1, 'FormAsteriskExplanation', 'FormAsteriskExplanation'),
(140, 1, 'WellRegistryIncompleteText', 'WellRegistryIncompleteText'),
(141, 1, 'ReferenceWellsList', 'Reference Wells List'),
(142, 2, 'ReferenceWellsUploader', 'Reference Wells Uploader'),
(143, 1, 'LandingPageBody', 'Landing Page Body'),
(144, 1, 'LandingPageUserCard', 'Landing Page User Card'),
(145, 1, 'LandingPageParcelCard', 'Landing Page Parcel Card'),
(146, 1, 'LandingPageWellCard', 'Landing Page Well Card'),
(147, 1, 'LandingPageWaterAccountCard', 'Landing Page Water Account Card'),
(148, 1, 'LandingPageOverview', 'Landing Page Overview'),
(149, 1, 'LandingPageAllocationPlans', 'Landing Page Allocation Plans'),
(150, 1, 'LandingPageWaterLevels', 'Landing Page Water Levels'),
(151, 1, 'LandingPageContact', 'Landing Page Contact'),
(152, 1, 'ConfigureLandingPage', 'ConfigureLandingPage'),
(153, 1, 'HomepageUpdateProfileLink', 'Homepage Update Profile Link'),
(154, 1, 'HomepageGrowerGuideLink', 'Homepage Grower Guide Link'),
(155, 1, 'HomepageGeographiesLink', 'Homepage Geographies Link'),
(156, 1, 'HomepageClaimWaterAccountsPanel', 'Homepage Claim Water Accounts Panel'),
(157, 3, 'ParcelStatus', 'Parcel Status'),
(158, 1, 'OnboardOverviewContent', 'Onboard Overview Content'),
(159, 1, 'ParcelBulkActions', 'Parcel Bulk Actions'),
(160, 1, 'MeterList', 'Meter List'),
(161, 3, 'SerialNumber', 'Serial Number'),
(162, 1, 'MeterConfiguration', 'Meter Configuration'),
(163, 1, 'Acknowledgements', 'Acknowledgements'),
(164, 1, 'AdminGeographyEditForm', 'Admin Geography Edit Form'),
(165, 1, 'LandingPageConfigure', 'Landing Page Configure'),
(166, 1, 'MeterDataConfigure', 'Meter Data Configure'),
(167, 1, 'AllocationPlanConfigureCard', 'Allocation Plan Configure Card'),
(168, 2, 'WellStatus', 'Well Status'),
(169, 1, 'UpdateWellInfo', 'Update Well Info'),
(170, 1, 'UpdateWellLocation', 'UpdateWellLocation'),
(171, 1, 'UpdateWellIrrigatedParcels', 'Update Well Irrigated Parcels'),
(172, 1, 'AdminFAQ', 'Admin Frequently Asked Questions'),
(173, 1, 'GeneralFAQ', 'General Frequently Asked Questions'),
(174, 1, 'WaterAccountCustomAttributesEdit', 'Edit Water Account Attributes'),
(175, 1, 'ParcelCustomAttributesEdit', 'Edit Parcel Attributes'),
(176, 1, 'WaterDashboardLink', 'Water Dashboard Link'),
(177, 1, 'WaterManagerGuideLink', 'Water Manager Guide Link'),
(178, 1, 'ReviewParcelChanges', 'Review Parcel Changes'),
(179, 1, 'WaterAccountRequestChanges', 'Request Water Account Changes'),
(180, 1, 'WaterAccountRequestChangesCertification', 'Request Water Account Changes Certification'),
(181, 1, 'ConsolidateWaterAccountsDisclaimer', 'Consolidate Water Accounts Disclaimer'),
(182, 1, 'KernScenarioModel', 'Kern Scenario Model'),
(183, 1, 'MercedWaterResourcesModel', 'Merced Water Resources Model'),
(184, 1, 'YoloScenarioModel', 'Yolo Scenario Model'),
(185, 1, 'ConfigureGeographySetup', 'Configure Geography Setup'),
(186, 1, 'ConfigureCustomAttributes', 'Configure Custom Attributes'),
(187, 1, 'ConfigureWaterManagers', 'Configure Water Managers'),
(188, 1, 'RasterUploadGuidance', 'Raster Upload Guidance')
)
AS Source (CustomRichTextTypeID, ContentTypeID, CustomRichTextTypeName, CustomRichTextTypeDisplayName)
ON Target.CustomRichTextTypeID = Source.CustomRichTextTypeID
WHEN MATCHED THEN
UPDATE SET
	ContentTypeID = Source.ContentTypeID,
	CustomRichTextTypeName = Source.CustomRichTextTypeName,
	CustomRichTextTypeDisplayName = Source.CustomRichTextTypeDisplayName
WHEN NOT MATCHED BY TARGET THEN
	INSERT (CustomRichTextTypeID, ContentTypeID, CustomRichTextTypeName, CustomRichTextTypeDisplayName)
	VALUES (CustomRichTextTypeID, ContentTypeID, CustomRichTextTypeName, CustomRichTextTypeDisplayName)
WHEN NOT MATCHED BY SOURCE THEN
	DELETE;
