CREATE TABLE [dbo].[Geography](
	[GeographyID] [int] NOT NULL CONSTRAINT [PK_Geography_GeographyID] PRIMARY KEY,
	[GeographyConfigurationID] INT not NULL CONSTRAINT [AK_Geography_GeographyConfigurationID] UNIQUE CONSTRAINT [FK_Geography_GeographyConfiguration_GeographyConfigurationID_GeographyConfigurationID] FOREIGN KEY REFERENCES dbo.[GeographyConfiguration](GeographyConfigurationID),
	[GeographyName] [varchar](50) NOT NULL CONSTRAINT [AK_Geography_GeographyName] UNIQUE,
	[StartYear] [int] NOT NULL DEFAULT 2016,
	[GeographyDisplayName] [varchar](100) NOT NULL CONSTRAINT [AK_Geography_GeographyDisplayName] UNIQUE,
	[GeographyDescription] varchar(500) null,
	[APNRegexPattern] varchar(100) NOT NULL,
	[APNRegexPatternDisplay] varchar(50) NOT NULL,
	[IsOpenETActive] bit NOT NULL default 0,
	OpenETShapeFilePath varchar(100) null,
	OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier varchar(50) null,
	CoordinateSystem int not null,
	AreaToAcresConversionFactor int not null, 
    [IsDemoGeography] BIT NOT NULL DEFAULT 0,
	[GSACanonicalID] INT NULL,
	[Color] varchar(9) null,
	[SourceOfRecordWaterMeasurementTypeID] INT NULL CONSTRAINT [FK_Geography_WaterMeasurementType_SourceOfRecordWaterMeasurementTypeID_WaterMeasurementTypeID] FOREIGN KEY REFERENCES dbo.[WaterMeasurementType](WaterMeasurementTypeID),
	[SourceOfRecordExplanation] varchar(500) NULL,
	[ContactEmail] varchar(100) NULL,
	[ContactPhoneNumber] VARCHAR (30) NULL,
	DefaultDisplayYear int not null default(2023),
	[LandownerDashboardSupplyLabel] varchar(200) not null default('Supply'),
	[LandownerDashboardUsageLabel] varchar(200) not null default('Usage'),
	DisplayUsageGeometriesAsField bit not null default(0),
	AllowLandownersToRequestAccountChanges bit not null default(0)
)
