CREATE TABLE dbo.WellRegistrationMetadatum
(
	WellRegistrationMetadatumID int not null IDENTITY(1,1) constraint PK_WellRegistrationMetadatum_WellRegistrationMetadatumID primary key,
	WellRegistrationID int not null constraint FK_WellRegistrationMetadatum_WellRegistration_WellRegistrationID foreign key references dbo.WellRegistration(WellRegistrationID) constraint AK_WellRegistrationMetadatum_WellRegistrationID unique,
	WellName varchar(100) null,
	StateWellNumber varchar(100) null,
	StateWellCompletionNumber varchar(100) null,
	CountyWellPermit varchar(100) null,
	DateDrilled date null,
	WellDepth int null,
	CasingDiameter int null,
	TopOfPerforations int null,
	BottomOfPerforations int null,
	ManufacturerOfWaterMeter varchar(100) null,
	SerialNumberOfWaterMeter varchar(100) null,
	ElectricMeterNumber varchar(100) null,
	PumpDischargeDiameter decimal(10,4) null,
	MotorHorsePower decimal(10,4) null,
	FuelTypeID int null constraint FK_WellRegistrationMetadatum_FuelType_FuelTypeID foreign key references dbo.FuelType(FuelTypeID), 
	FuelOther varchar(100) null,
	MaximumFlow int null,
	[IsEstimatedMax] bit null,
	TypicalPumpFlow int null,
	[IsEstimatedTypical] bit null,
	PumpTestBy varchar(100) null,
	PumpTestDatePerformed date null,
	PumpManufacturer varchar(100) null,
	PumpYield int null,
	PumpStaticLevel int null,
	PumpingLevel int null
)
