version: '3.5'

services:
  testdb:    
    container_name: mssql-server-test
    image: mcr.microsoft.com/mssql/server
    environment:
       SA_PASSWORD: password#1
       ACCEPT_EULA: "Y"
       MSSQL_PID: Express
    ports:
      - "1443:1433"