import { Component, Input } from "@angular/core";

@Component({
    selector: "icon",
    imports: [],
    templateUrl: "./icon.component.html",
    styleUrls: ["./icon.component.scss"]
})
export class IconComponent {
    @Input() icon: IconInterface;
    @Input() enableFontSize: boolean = false;
}

export const ICONS = [
    "ActivityCenter",
    "Allocations",
    "AngleUp",
    "AngleDown",
    "ArrowLeft",
    "Budget",
    "BulletedList",
    "Calendar",
    "Calculator",
    "CaretDown",
    "CaretUp",
    "ChatBubble",
    "Clipboard",
    "CircleCheckmark",
    "CirclePencil",
    "CircleX",
    "Code",
    "Configure",
    "Contact",
    "DataLayers",
    "Delete",
    "Download",
    "Dollar",
    "Drag",
    "ExternalLink",
    "File",
    "Geography",
    "Geography-Alt",
    "Guide",
    "Inbox",
    "Info",
    "Layout",
    "License",
    "LineChart",
    "LineChartTrendingUp",
    "LineChartTrendingDown",
    "Logo",
    "Manage",
    "Map",
    "Measurements",
    "Meter",
    "Model",
    "News",
    "Note",
    "Parcels",
    "PlusSquare",
    "Question",
    "Resend",
    "Review",
    "ReviewApprove",
    "ReviewReturn",
    "Satellite",
    "ScenarioPlanner",
    "ScenarioRun",
    "Star",
    "Statement",
    "Statistics",
    "StepComplete",
    "StepIncomplete",
    "SupportLogo",
    "Transactions",
    "Upload",
    "User",
    "Users",
    "VerticalMap",
    "Warning",
    "WaterAccounts",
    "WaterDrop",
    "WaterDropFilled",
    "WaterSupply",
    "Wells",
    "Zones",
];

export type IconInterface = (typeof ICONS)[number];
